#!/bin/sh
if [ "$#" -ne 0 ]; then
	echo "usage: $0" >&2
	exit 1
fi

TMP=$(mktemp)
cat > $TMP;

FORMAT=$(file -ib $TMP | cut -d ";" -f 1);

case "$FORMAT" in
    image/png)  png2ff < $TMP; ret=$? ;;
    image/jpeg) jpg2ff < $TMP; ret=$? ;;
    *) xconvert $TMP png:- 2&>/dev/null | png2ff 2&>/dev/null; ret=$? ;;
esac

rm $TMP;

if [ $ret -ne 0 ]; then
	printf "%s: failed to convert %s\n" "$0" "$FORMAT" 1>&2;
fi

exit $ret;
