.Dd 2016-03-23
.Dt FF2JPG 1
.Os suckless.org
.Sh NAME
.Nm ff2jpg
.Nd convert farbfeld to JPEG
.Sh SYNOPSIS
.Nm
.Op Fl b Ar color
.Op Fl o
.Op Fl q Ar quality
.Sh DESCRIPTION
.Nm
reads a
.Xr farbfeld 5
image from stdin, converts it to a JPEG image (RGB) and writes the result to
stdout.
.Pp
In case of an error
.Nm
writes a diagnostic message to stderr.
.Sh OPTIONS
.Bl -tag -width Ds
.It Fl b Ar color
.Ar color
to mix with the background alpha channel, the default is white.
.Pp
The following formats are supported:
"#rrggbb", "#rrrrggggbbbb" and the short-form "#rgb" which expands to "#rrggbb".
.It Fl o
Optimize Huffman table (smaller file, but slow compression).
.It Fl q Ar quality
set JPEG output
.Ar quality
(range 0-100), the default is 85.
.El
.Sh EXIT STATUS
.Bl -tag -width Ds
.It 0
Image processed successfully.
.It 1
An error occurred.
.El
.Sh EXAMPLES
$
png2ff < test.png |
.Nm
-b '#00ff00' -q 85 > test.jpg
.Sh SEE ALSO
.Xr 2ff 1 ,
.Xr bunzip2 1 ,
.Xr bzip2 1 ,
.Xr png2ff 1 ,
.Xr farbfeld 5
.Sh AUTHORS
.An Hiltjo Posthuma Aq Mt hiltjo@codemadness.org
