.Dd 2016-03-21
.Dt FF2PPM 1
.Os suckless.org
.Sh NAME
.Nm ff2ppm
.Nd convert farbfeld to PPM (binary)
.Sh SYNOPSIS
.Nm
.Op Fl b Ar color
.Sh DESCRIPTION
.Nm
reads a
.Xr farbfeld 5
image from stdin, converts it to a PPM image (P6 binary format, RGB) and
writes the result to stdout.
.Pp
In case of an error
.Nm
writes a diagnostic message to stderr.
.Sh OPTIONS
.Bl -tag -width Ds
.It Fl b Ar color
.Ar color
to mix with the background alpha channel, the default is white.
.Pp
The following formats are supported:
"#rrggbb", "#rrrrggggbbbb" and the short-form "#rgb" which expands to "#rrggbb".
.El
.Sh EXIT STATUS
.Bl -tag -width Ds
.It 0
Image processed successfully.
.It 1
An error occurred.
.El
.Sh EXAMPLES
$
png2ff < test.png |
.Nm
-b '#00ff00' > test.ppm
.Sh SEE ALSO
.Xr 2ff 1 ,
.Xr bunzip2 1 ,
.Xr bzip2 1 ,
.Xr png2ff 1 ,
.Xr farbfeld 5
.Sh AUTHORS
.An Hiltjo Posthuma Aq Mt hiltjo@codemadness.org
